//! The one module in knobas that assembles a SQL statement at runtime.
//!
//! Roadmap §4 gotcha 2, verbatim: *"sqlx 0.9: dynamic SQL needs
//! `AssertSqlSafe`; keep it in one reviewed query-builder module. Never bind
//! `tsquery` -- bind text into `websearch_to_tsquery('english', $1)`, compute
//! the tsquery once as a FROM item. Never map `tsvector` to `String`."* This is
//! that module, and `tests/sql_containment.rs` fails the build if anything else
//! in the crate so much as names the type.
//!
//! # Why the confinement holds
//!
//! Three things, in order of how much they are worth:
//!
//! 1. **Types.** [`SearchSql`]'s fields are private and the builders in this
//!    module are its only constructors, so no caller anywhere can hand
//!    [`query_as_with`] a string it made up. The escape hatch is not merely
//!    discouraged, it is unreachable.
//! 2. **The `Corpus` invariant.** Every fragment spliced into the statement is
//!    a `&'static str` from [`crate::corpus`]; every value -- every word the
//!    user typed, every source id, every kind, every limit -- travels as a
//!    bind, and the *only* way to add one is [`Builder::param`], which returns
//!    the placeholder that reads it. A placeholder therefore cannot drift from
//!    its argument. The one piece of runtime-formatted text is the corpus
//!    index, a loop counter over the caller's own slice.
//! 3. **A test**, for the day someone in a hurry adds a fourth thing.
//!
//! # The shape of the statement, and why
//!
//! ```sql
//! with q as (...),                 -- the tsquery, computed once
//!      m as materialized (...),    -- one narrow row per *match*
//!      totals as (...),            -- per-kind counts, over every match
//!      top as (...),               -- rank within kind
//!      picked as (...),            -- the page
//!      detail as (...)             -- titles and excerpts, page only
//! select ... from totals left join detail ...
//! ```
//!
//! Four properties are load-bearing:
//!
//! * **`m` is deliberately narrow** -- entity id, kind, rank, updated-at and
//!   nothing else. It holds one row per match, which for a common word is
//!   thousands; carrying titles and bodies through it is what turns a 20 ms
//!   search into a 200 ms one.
//! * **Exactly one match scan.** `m` is `materialized` because both `totals`
//!   and `top` read it, and the alternative is scanning the index twice.
//! * **`totals` LEFT JOIN `detail`**, so every matching kind comes back even
//!   when the global `limit` left it no row: `ResultGroup.total` is then a true
//!   count and not a page size. A kind with `total > 0` and no hit is a
//!   legitimate row, and the columns of such a row are **null** -- the caller's
//!   `FromRow` must read them as `Option`.
//! * **`ts_headline` runs after the limit.** It re-parses the document text per
//!   row, and running it over the match set instead of over the page is the
//!   single most expensive mistake available here.
//!
//! # The second statement, and why it is a second one
//!
//! [`saved_summary_sql`] (#506) answers *how many rows are in this saved list,
//! and how fresh is the newest of them* for every saved list at once. It is a
//! separate builder rather than a mode of [`search_sql`] because it shares
//! exactly one thing with a search -- the `where` clause -- and none of the six
//! stages above: no ranking, no per-kind cap, no page, no titles, no excerpts.
//! The one thing they do share is generated by one function,
//! [`corpus_predicates`], so the number on the rail and the rows behind it
//! cannot come from two different readings of the same query.
//!
//! This replaces the contract seed's two statements, whose per-kind total was a
//! `count(*) over (partition by kind)` -- a second window partition, and
//! therefore a second full sort of every matching row, on the launcher's hot
//! path (M0 carry-over). `totals` is one grouped aggregate over the same
//! materialized scan.

use std::fmt::Write as _;

use sqlx::postgres::{PgArguments, PgRow};
use sqlx::query::QueryAs;
use sqlx::{FromRow, Postgres};

use crate::corpus::Corpus;
use crate::query::EffectiveFilters;

/// One value bound into a generated statement.
///
/// Deliberately closed and deliberately small: every variant here is something
/// the builder actually binds, so a variant nobody constructs is a variant
/// nobody has to review.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum Bind {
    /// The raw search text, and the `ts_headline` options.
    Text(String),
    /// A `text[]` for an `= any(...)` predicate.
    Texts(Vec<String>),
    /// `make_interval(days => ...)`, which takes an `int4`.
    I32(i32),
    /// Row counts: `row_number()` yields `bigint`, and so does `limit`.
    I64(i64),
}

/// A generated statement and the arguments that go with it.
///
/// The fields are private and the two builders in this module -- [`search_sql`]
/// and [`saved_summary_sql`] -- are its only constructors. That is not
/// tidiness: it is what makes "runtime SQL is confined to this module" a
/// property of the type system rather than of a convention, and adding a
/// builder does not weaken it, because a caller still cannot hand
/// [`query_as_with`] a string of its own.
#[derive(Debug, Clone)]
pub struct SearchSql {
    sql: String,
    binds: Vec<Bind>,
}

impl SearchSql {
    /// The generated statement, for tests and for tracing.
    #[must_use]
    pub fn sql(&self) -> &str {
        &self.sql
    }

    /// How many arguments the statement expects.
    #[must_use]
    pub fn bind_count(&self) -> usize {
        self.binds.len()
    }
}

/// Assemble the launcher's query.
///
/// * `corpora` -- the relations to search. M1 passes `&[&LIVE_ITEM]`; more than
///   one becomes a `union all` inside the match CTE.
/// * `text` -- the search terms, or `None` for **browse mode**: no ranking, no
///   excerpts, ordered by recency. A browse with no filters at all is refused
///   upstream rather than counting the whole corpus.
/// * `prefix_last` -- whether the last word is still being typed and should
///   match as a prefix.
/// * `per_group` -- how many rows one kind may contribute, so a flood of
///   tickets cannot push every build off the page.
/// * `limit` -- the total number of rows returned.
#[must_use]
pub fn search_sql(
    corpora: &[&Corpus],
    text: Option<&str>,
    prefix_last: bool,
    filters: &EffectiveFilters,
    per_group: u32,
    limit: u32,
) -> SearchSql {
    let mut builder = Builder::default();

    // Binds are allocated in the order their placeholders first appear in the
    // statement below. That is not cosmetic: it is what keeps `$1..$n` dense
    // and in order, which `placeholders_are_numbered_in_bind_order` pins.
    let tsquery = text.map(|raw| builder.param(Bind::Text(raw.to_owned())));
    let bound = bind_filters(&mut builder, filters);
    let per_group = builder.param(Bind::I64(i64::from(per_group)));
    let limit = builder.param(Bind::I64(i64::from(limit)));
    let headline_opts = text.map(|_| builder.param(Bind::Text(crate::snippet::headline_options())));

    let mut sql = String::from("with\n");

    if let Some(tsquery) = &tsquery {
        // Computed ONCE, as a FROM item, and never bound as a tsquery
        // (roadmap §4 gotcha 2): the match, the rank and the headline all read
        // this one value.
        sql.push_str("q as not materialized (\n  select ");
        if prefix_last {
            // What makes the box answer while the word is still being typed.
            // `websearch_to_tsquery` output is already a well-formed, quoted
            // tsquery, so appending ':*' to its *text* and casting back turns
            // only the last lexeme into a prefix. The guard is for the empty
            // case -- a query of nothing but stopwords yields the empty
            // tsquery, and ':*' on its own is a syntax error.
            sql.push_str(concat!(
                "case when t.tsq::text = '' then null::tsquery\n",
                "              else (t.tsq::text || ':*')::tsquery end as tsq\n"
            ));
        } else {
            sql.push_str("t.tsq as tsq\n");
        }
        let _ = writeln!(
            sql,
            "    from (select websearch_to_tsquery('english', {tsquery}) as tsq) t\n),"
        );
    }

    // One narrow row per match. MATERIALIZED because `totals` and `top` both
    // read it and the scan must happen once.
    sql.push_str("m as materialized (\n");
    for (index, corpus) in corpora.iter().enumerate() {
        if index > 0 {
            sql.push_str("  union all\n");
        }
        let rank = if text.is_some() {
            format!("ts_rank_cd({}, q.tsq)", corpus.fts)
        } else {
            "0::real".to_owned()
        };
        let _ = writeln!(
            sql,
            "  select {} as entity_id, {} as kind, {rank} as rank,\n         {} as item_updated_at, {index} as corpus",
            corpus.entity_id, corpus.kind, corpus.updated_at
        );
        let _ = write!(sql, "    from {}", corpus.relation);
        if text.is_some() {
            sql.push_str(" cross join q");
        }
        sql.push('\n');

        let predicates = corpus_predicates(corpus, text.is_some().then_some("q.tsq"), &bound);
        if !predicates.is_empty() {
            let _ = writeln!(sql, "   where {}", predicates.join("\n     and "));
        }
    }
    sql.push_str("),\n");

    // The true per-kind count, over every match rather than over the page.
    sql.push_str("totals as (select kind, count(*) as kind_total from m group by kind),\n");

    // One ordering, spelled three times with different qualifiers: within the
    // kind (window), across the page, and across the joined result. They must
    // agree, or the row a group header counts is not the row it shows.
    let ranked = text.is_some();
    let ordering = order_by("", ranked, false);

    let _ = writeln!(
        sql,
        "top as (\n  select m.*, row_number() over (partition by m.kind order by {}) as rn\n    from m\n),",
        order_by("m.", ranked, false)
    );
    // One kind cannot flood the box (rn), and the whole answer is bounded
    // (limit) before anything expensive touches it.
    let _ = writeln!(
        sql,
        "picked as (\n  select * from top where rn <= {per_group}\n   order by {ordering}\n   limit {limit}\n),"
    );

    // Titles and excerpts, on the rows that survived and no others.
    sql.push_str("detail as (\n");
    for (index, corpus) in corpora.iter().enumerate() {
        if index > 0 {
            sql.push_str("  union all\n");
        }
        let snippet = match &headline_opts {
            Some(opts) => format!(
                "ts_headline('english', {}, q.tsq, {opts})",
                corpus.headline_text
            ),
            None => "null::text".to_owned(),
        };
        let _ = writeln!(
            sql,
            "  select p.kind as kind, p.entity_id as entity_id, p.rank as rank,\n         p.item_updated_at as item_updated_at,\n         {} as source_id, {} as title, {} as synced_at,\n         {} as path,\n         {snippet} as snippet",
            corpus.source_id, corpus.title, corpus.synced_at, corpus.path
        );
        let _ = write!(sql, "    from picked p\n    join {}", corpus.relation);
        let _ = write!(sql, " on {} = p.entity_id", corpus.entity_id);
        if let Some(scope) = corpus.scope {
            let _ = write!(sql, " and {scope}");
        }
        sql.push('\n');
        if text.is_some() {
            sql.push_str("    cross join q\n");
        }
        // The discriminator, so two corpora that happen to share an entity id
        // cannot cross-join into each other's detail rows.
        let _ = writeln!(sql, "   where p.corpus = {index}");
    }
    sql.push_str(")\n");

    // A kind the limit cut has no detail row, so every `d.` column here is
    // null for it -- `nulls last` keeps those group headers at the end of
    // their kind rather than at the front of it.
    let _ = write!(
        sql,
        "select t.kind as group_kind, t.kind_total as kind_total,\n       d.entity_id as entity_id, d.source_id as source_id, d.title as title,\n       d.item_updated_at as updated_at, d.synced_at as synced_at,\n       d.path as path,\n       d.rank as rank, d.snippet as snippet\n  from totals t\n  left join detail d on d.kind = t.kind\n order by t.kind, {}",
        order_by("d.", ranked, true)
    );

    SearchSql {
        sql,
        binds: builder.binds,
    }
}

/// The filter placeholders one statement has allocated, ready to splice.
///
/// A struct rather than four locals so that [`corpus_predicates`] can be one
/// function with two callers: the placeholders are per **statement**, the
/// predicates are per **corpus**, and separating them is what lets the rail's
/// count and the page behind it be generated from one piece of code.
struct BoundFilters {
    sources: Option<String>,
    kinds: Option<String>,
    days: Option<String>,
    authors: Option<String>,
}

/// Allocate one statement's filter binds, in the order they are read.
fn bind_filters(builder: &mut Builder, filters: &EffectiveFilters) -> BoundFilters {
    BoundFilters {
        sources: (!filters.sources.is_empty())
            .then(|| builder.param(Bind::Texts(filters.sources.clone()))),
        kinds: (!filters.kinds.is_empty())
            .then(|| builder.param(Bind::Texts(filters.kinds.clone()))),
        days: filters
            .updated_within_days
            .map(|days| builder.param(Bind::I32(clamp_days(days)))),
        // `mine` with an empty author list is not "no filter": it is knobas not
        // knowing who the user is. Binding the empty array matches nothing,
        // which is the honest answer; dropping the predicate would return
        // everything.
        //
        // Which is why the *decision* reads `mine` and the named people rather
        // than the resolved list: the list is empty in exactly the state the
        // predicate has to survive.
        authors: filters
            .filters_by_author()
            .then(|| builder.param(Bind::Texts(filters.authors()))),
    }
}

/// What one corpus contributes to a `where` clause for a given query.
///
/// **One function, two statements**, and that is the whole reason it exists:
/// [`search_sql`] builds the rows a query answers with and
/// [`saved_summary_sql`] builds the number the launcher's rail draws beside it,
/// and `knobas_search::lists`' `builtins!` macro states the rule those two are
/// held to in as many words -- *"a count computed from a different predicate
/// than the rows it claims to count is the worst failure available here"*. The
/// built-ins get that guarantee from a macro because their predicates are
/// literals; a saved list's predicate is assembled at run time, so it gets it
/// from this.
///
/// `fts` is the expression the corpus's `tsvector` is matched against, or
/// `None` for a browse: `search_sql` computes the tsquery once as a `q` CTE and
/// passes `q.tsq`, and [`saved_summary_sql`] -- which has no rank and no
/// headline to feed and may carry several queries at once -- spells the call
/// inline. Either way the raw text travels as a bind and never as SQL.
fn corpus_predicates(corpus: &Corpus, fts: Option<&str>, bound: &BoundFilters) -> Vec<String> {
    let mut predicates: Vec<String> = Vec::new();
    if let Some(fts) = fts {
        predicates.push(format!("{} @@ {fts}", corpus.fts));
    }
    if let Some(scope) = corpus.scope {
        predicates.push(scope.to_owned());
    }
    if let Some(sources) = &bound.sources {
        predicates.push(format!("{} = any({sources})", corpus.source_id));
    }
    if let Some(kinds) = &bound.kinds {
        predicates.push(format!("{} = any({kinds})", corpus.kind));
    }
    if let Some(days) = &bound.days {
        predicates.push(format!(
            "{} >= now() - make_interval(days => {days})",
            corpus.updated_at
        ));
    }
    if let Some(authors) = &bound.authors {
        predicates.push(match corpus.author {
            Some(author) => format!("{author} = any({authors})"),
            // A corpus with no author column holds nothing of anybody's.
            None => "false".to_owned(),
        });
    }
    predicates
}

/// One saved list, as the summary statement asks about it (#506).
///
/// The parse is the caller's -- `knobas_search::saved` runs the saved raw text
/// through the same `query::parse` + `query::merge` a keystroke goes through,
/// so what arrives here is the query *as the grammar of the day reads it* and
/// not as it read when somebody pressed *Save as list*.
#[derive(Debug)]
pub struct SavedQuery<'a> {
    /// The list's id, echoed back as a column so that one statement can answer
    /// for every saved list at once. Bound, never spliced.
    pub id: &'a str,
    /// The search terms, or `None` for a saved query that is nothing but chips
    /// -- browse mode, exactly as in [`search_sql`].
    pub text: Option<&'a str>,
    pub filters: &'a EffectiveFilters,
}

/// Every saved list's count and freshness, in one round trip.
///
/// `None` when there is nothing to ask about, which is the ordinary case: a
/// launcher with no saved lists must not send a statement at all, and an empty
/// `union all` is not a statement.
///
/// # The shape, and what is deliberately absent from it
///
/// ```sql
/// select $1 as list_id, count(*) as total, max(m.synced_at) as newest
///   from ( <one branch per corpus, the same where clause a search uses> ) m
/// union all
/// select $7 as list_id, ...
/// ```
///
/// No `q` CTE, no `materialized`, no `totals`, no `top`, no `picked`, no
/// `detail` and no `ts_headline`. Every one of those exists in [`search_sql`]
/// to produce a **page** -- to rank it, to bound it per kind, and to fetch
/// titles and excerpts for the rows that survived. A rail draws a number and a
/// dot; it reads no row, so the branch stays as narrow as `m` is there and the
/// most expensive stage of a search never runs for it.
///
/// **One statement for every saved list**, `union all`-ed, because the board is
/// one round trip: `lists::SUMMARY_SQL` answers the seven built-ins in one and
/// a rail that then made a round trip per saved list would grow the launcher's
/// hot path by the number of lists a reader has saved. The work is the same
/// scans either way; what is saved is the latency, which is what the ⌘K budget
/// is spent on.
///
/// **`max(synced_at)`, not `max(item_updated_at)`**, and the built-ins are why:
/// `SUMMARY_SQL`'s mirror lists badge on `max(i.synced_at)`, so "something in
/// this list is newer than the last time you opened it" means *knobas has seen
/// something since* for a saved list exactly as it does for *Changed today*. An
/// item the source last moved a year ago that a sync brought into a saved
/// list's reach this morning is news, and `item_updated_at` would call it a
/// year old.
#[must_use]
pub fn saved_summary_sql(corpora: &[&Corpus], queries: &[SavedQuery<'_>]) -> Option<SearchSql> {
    if queries.is_empty() {
        return None;
    }
    let mut builder = Builder::default();
    let mut sql = String::new();

    for (position, query) in queries.iter().enumerate() {
        if position > 0 {
            sql.push_str("union all\n");
        }
        // Binds in the order their placeholders appear, as in `search_sql`:
        // the id column first, then the tsquery, then the filters.
        let id = builder.param(Bind::Text(query.id.to_owned()));
        let fts = query.text.map(|raw| {
            let text = builder.param(Bind::Text(raw.to_owned()));
            format!("websearch_to_tsquery('english', {text})")
        });
        let bound = bind_filters(&mut builder, query.filters);

        let _ = writeln!(
            sql,
            "select {id} as list_id, count(*) as total, max(m.synced_at) as newest\n  from ("
        );
        for (index, corpus) in corpora.iter().enumerate() {
            if index > 0 {
                sql.push_str("  union all\n");
            }
            let _ = writeln!(
                sql,
                "  select {} as synced_at\n    from {}",
                corpus.synced_at, corpus.relation
            );
            let predicates = corpus_predicates(corpus, fts.as_deref(), &bound);
            if !predicates.is_empty() {
                let _ = writeln!(sql, "   where {}", predicates.join("\n     and "));
            }
        }
        sql.push_str("  ) m\n");
    }

    Some(SearchSql {
        sql,
        binds: builder.binds,
    })
}

/// Bind a generated statement and hand back a runnable query.
///
/// The one place in knobas where a runtime-built SQL string is executed. Sound
/// because of the invariants in this module's docs: `built.sql` came out of
/// [`search_sql`], which can only concatenate `&'static str` fragments and
/// placeholders produced by [`Builder::param`].
pub fn query_as_with<O>(built: SearchSql) -> QueryAs<'static, Postgres, O, PgArguments>
where
    O: for<'r> FromRow<'r, PgRow> + Send + Unpin,
{
    let SearchSql { sql, binds } = built;
    let mut query = sqlx::query_as::<Postgres, O>(sqlx::AssertSqlSafe(sql))
        // **Not a cached prepared statement, and this is a measured decision.**
        //
        // PostgreSQL plans a *named* prepared statement with the actual
        // parameter values for its first five executions and then considers a
        // **generic** plan, which by definition cannot know the tsquery. It
        // therefore falls back to a default selectivity guess for `fts @@ $1`,
        // decides the match set is tiny, and joins `knobas.entity` with a
        // nested loop -- one `entity_pkey` probe per matching row.
        //
        // Measured on a 100k-row corpus, twenty consecutive searches for one
        // word: 125, 123, 124, 123, 128, **185**, 187, 185, 196, 191, 230, 284,
        // 257, 347, 502, 621, ... The step at the sixth execution is the switch.
        // The plan behind the slow one does 40,000 index probes and touches
        // 167,554 buffers where the custom plan's hash join touches 8,386.
        //
        // `persistent(false)` uses the unnamed statement, which PostgreSQL
        // plans at Bind time with the values in hand -- so every execution is a
        // custom plan. The cost is re-planning: 1.5 ms of a 100 ms budget,
        // against a 5x regression that only appears after the sixth keystroke
        // of a session and would therefore never be seen in a test that ran a
        // query five times.
        .persistent(false);
    for bind in binds {
        query = match bind {
            Bind::Text(value) => query.bind(value),
            Bind::Texts(value) => query.bind(value),
            Bind::I32(value) => query.bind(value),
            Bind::I64(value) => query.bind(value),
        };
    }
    query
}

/// The plan the launcher's own statement runs under.
///
/// Behind `test-util` and living **here** because this is the module
/// `AssertSqlSafe` is confined to (`tests/sql_containment.rs` fails the build
/// if it is named anywhere else). Prepending `explain` to a statement built by
/// [`search_sql`] is exactly as sound as running it: the text still came out of
/// the builder and every value still travels as a bind.
///
/// `analyze` and `buffers` on, `costs` off -- the estimate is not the question,
/// what the executor actually did is.
///
/// # Errors
///
/// [`sqlx::Error`] if the statement cannot be planned.
#[cfg(any(test, feature = "test-util"))]
pub async fn explain(pool: &sqlx::PgPool, built: SearchSql) -> Result<String, sqlx::Error> {
    let SearchSql { sql, binds } = built;
    let mut query = sqlx::query_as::<Postgres, (String,)>(sqlx::AssertSqlSafe(format!(
        "explain (analyze, buffers, costs off)
{sql}"
    )));
    for bind in binds {
        query = match bind {
            Bind::Text(value) => query.bind(value),
            Bind::Texts(value) => query.bind(value),
            Bind::I32(value) => query.bind(value),
            Bind::I64(value) => query.bind(value),
        };
    }
    Ok(query
        .fetch_all(pool)
        .await?
        .into_iter()
        .map(|(line,)| line)
        .collect::<Vec<_>>()
        .join("\n"))
}

/// The largest `updated:` window the statement may ask Postgres for.
///
/// `now() - make_interval(days => $n)` has to land inside `timestamptz`, which
/// bottoms out at 4713 BC -- about 2.4 million days back. Past that the server
/// raises `timestamp out of range`, and the launcher turns a typo into an
/// `IpcErrorCode::Internal` on its hot path.
///
/// Roughly 2,700 years, which is longer than any corpus and comfortably inside
/// the range. The exact number does not matter; that it is a **clamp** and not
/// a saturation does. Saturating at `i32::MAX` is the worst possible choice --
/// that value is itself guaranteed to throw.
const MAX_UPDATED_WITHIN_DAYS: i32 = 1_000_000;

/// A day count Postgres can subtract from `now()`.
///
/// Clamped here rather than in the parser, and deliberately so: `SearchFilters`
/// arrives from the frontend, so a **chip** carrying `updated_within_days:
/// 4_294_967_295` never passes through `query::duration_days` at all. The
/// engine's limit belongs at the engine's edge, which is the only place every
/// caller goes through.
fn clamp_days(days: u32) -> i32 {
    i32::try_from(days)
        .unwrap_or(MAX_UPDATED_WITHIN_DAYS)
        .min(MAX_UPDATED_WITHIN_DAYS)
}

/// The result ordering, qualified with `prefix` (`""`, `"m."` or `"d."`).
///
/// `entity_id` is the last key on purpose: rank ties and identical timestamps
/// are common in a mirror written by one transaction, and without a total order
/// the page a user pages through is not stable between two identical queries.
fn order_by(prefix: &str, ranked: bool, nullable: bool) -> String {
    let nulls = if nullable { " nulls last" } else { "" };
    let mut keys = Vec::new();
    if ranked {
        keys.push(format!("{prefix}rank desc{nulls}"));
    }
    keys.push(format!("{prefix}item_updated_at desc nulls last"));
    keys.push(format!("{prefix}entity_id"));
    keys.join(", ")
}

/// Accumulates the arguments a generated statement reads.
#[derive(Default)]
struct Builder {
    binds: Vec<Bind>,
}

impl Builder {
    /// Push a value and get back the placeholder that reads it.
    ///
    /// The only way to add a bind, which is what makes it impossible for a
    /// placeholder to drift from its argument.
    fn param(&mut self, bind: Bind) -> String {
        self.binds.push(bind);
        format!("${}", self.binds.len())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::corpus::LIVE_ITEM;

    /// Every single-quoted literal the builder is allowed to emit.
    ///
    /// The point of the list is that it is *closed*: a generated statement that
    /// contains a quoted string not named here is either a new static fragment
    /// nobody reviewed, or -- the case that matters -- user text that reached
    /// the SQL instead of the bind list.
    /// The last six are `ancestor_path_read!`'s (#284): the payload keys it
    /// walks, the three `jsonb_typeof` comparands it guards on, and the
    /// separator it joins a path with. They are `concat!`ed `&'static str`s inside that macro, so
    /// no value can reach them -- and naming them here is what keeps this list
    /// closed rather than widened.
    const ALLOWED_LITERALS: &[&str] = &[
        "english",
        ":*",
        "",
        " — ",
        "ancestors",
        "title",
        "array",
        "object",
        "string",
        " \u{203a} ",
    ];

    fn filters(
        sources: &[&str],
        kinds: &[&str],
        days: Option<u32>,
        authors: &[&str],
    ) -> EffectiveFilters {
        EffectiveFilters {
            sources: sources.iter().map(|s| (*s).to_owned()).collect(),
            kinds: kinds.iter().map(|s| (*s).to_owned()).collect(),
            updated_within_days: days,
            mine: !authors.is_empty(),
            identity_authors: authors.iter().map(|s| (*s).to_owned()).collect(),
            named_authors: Vec::new(),
        }
    }

    /// Every `'...'` run in a statement, in order.
    fn literals(sql: &str) -> Vec<String> {
        let mut out = Vec::new();
        let mut rest = sql;
        while let Some(start) = rest.find('\'') {
            rest = &rest[start + 1..];
            let end = rest.find('\'').expect("an unterminated literal");
            out.push(rest[..end].to_owned());
            rest = &rest[end + 1..];
        }
        out
    }

    /// Every `$n`, in order of first appearance.
    fn placeholders(sql: &str) -> Vec<usize> {
        let mut seen: Vec<usize> = Vec::new();
        let bytes = sql.as_bytes();
        for (index, byte) in bytes.iter().enumerate() {
            if *byte != b'$' {
                continue;
            }
            let digits: String = sql[index + 1..]
                .chars()
                .take_while(char::is_ascii_digit)
                .collect();
            if digits.is_empty() {
                continue;
            }
            let n: usize = digits.parse().expect("a number");
            if !seen.contains(&n) {
                seen.push(n);
            }
        }
        seen
    }

    #[test]
    fn user_text_never_enters_the_sql_string() {
        let evil = "'; drop schema knobas cascade; --";
        let built = search_sql(
            &[&LIVE_ITEM],
            Some(evil),
            false,
            &filters(&[evil], &[evil], None, &[evil]),
            10,
            50,
        );
        assert!(!built.sql.contains("drop schema"), "{}", built.sql);
        assert!(!built.sql.contains(evil), "{}", built.sql);
        // Stronger than "does not contain that string": the set of literals in
        // the statement is closed, so *no* user text can be hiding in it.
        for literal in literals(&built.sql) {
            assert!(
                ALLOWED_LITERALS.contains(&literal.as_str()),
                "unexpected literal {literal:?} in\n{}",
                built.sql
            );
        }
        // Everything the user typed arrived as a bind instead.
        assert!(
            built
                .binds
                .iter()
                .any(|bind| matches!(bind, Bind::Text(text) if text == evil))
        );
        assert!(
            built
                .binds
                .iter()
                .any(|bind| matches!(bind, Bind::Texts(values) if values == &[evil.to_owned()]))
        );
    }

    #[test]
    fn placeholders_are_numbered_in_bind_order() {
        let built = search_sql(
            &[&LIVE_ITEM],
            Some("sepa"),
            true,
            &filters(&["jira"], &["ticket"], Some(7), &["mara"]),
            10,
            50,
        );
        assert_eq!(built.binds.len(), 8, "{}", built.sql);
        assert_eq!(
            placeholders(&built.sql),
            (1..=built.binds.len()).collect::<Vec<_>>(),
            "{}",
            built.sql
        );
        // And the arguments are the ones the placeholders promise.
        assert_eq!(built.binds[0], Bind::Text("sepa".to_owned()));
        assert_eq!(built.binds[1], Bind::Texts(vec!["jira".to_owned()]));
        assert_eq!(built.binds[2], Bind::Texts(vec!["ticket".to_owned()]));
        assert_eq!(built.binds[3], Bind::I32(7));
        assert_eq!(built.binds[4], Bind::Texts(vec!["mara".to_owned()]));
        assert_eq!(built.binds[5], Bind::I64(10));
        assert_eq!(built.binds[6], Bind::I64(50));
    }

    /// A statement with no filters must number its placeholders densely too --
    /// the bind list shrinks with the predicates, and a gap would be a query
    /// that reads an argument nobody sent.
    #[test]
    fn a_bare_query_still_numbers_densely() {
        let built = search_sql(
            &[&LIVE_ITEM],
            Some("sepa"),
            false,
            &EffectiveFilters::default(),
            10,
            50,
        );
        assert_eq!(built.binds.len(), 4);
        assert_eq!(placeholders(&built.sql), [1, 2, 3, 4], "{}", built.sql);
    }

    #[test]
    fn the_tsquery_is_computed_once_and_the_trailing_word_may_be_a_prefix() {
        let typing = search_sql(
            &[&LIVE_ITEM],
            Some("sep"),
            true,
            &EffectiveFilters::default(),
            10,
            50,
        );
        assert_eq!(
            typing.sql.matches("websearch_to_tsquery").count(),
            1,
            "the tsquery is computed once, as a FROM item: {}",
            typing.sql
        );
        assert_eq!(
            typing.sql.matches("cross join q").count(),
            2,
            "and it is read as a FROM item by the match and by the headline: {}",
            typing.sql
        );
        assert!(typing.sql.contains("':*'"), "{}", typing.sql);
        // The empty-tsquery guard: `':*'` appended to nothing is a syntax
        // error, not an empty match.
        assert!(typing.sql.contains("null::tsquery"), "{}", typing.sql);

        let done = search_sql(
            &[&LIVE_ITEM],
            Some("sepa"),
            false,
            &EffectiveFilters::default(),
            10,
            50,
        );
        assert!(!done.sql.contains("':*'"), "{}", done.sql);
        assert_eq!(done.sql.matches("websearch_to_tsquery").count(), 1);
    }

    #[test]
    fn an_absent_filter_emits_no_predicate() {
        let bare = search_sql(
            &[&LIVE_ITEM],
            Some("x"),
            false,
            &EffectiveFilters::default(),
            10,
            50,
        );
        for absent in [
            "source_id = any",
            "kind = any",
            "make_interval",
            "author = any",
        ] {
            assert!(
                !bare.sql.contains(absent),
                "{absent} leaked into an unfiltered query:\n{}",
                bare.sql
            );
        }
    }

    #[test]
    fn a_present_filter_emits_exactly_its_predicate() {
        let built = search_sql(
            &[&LIVE_ITEM],
            Some("x"),
            false,
            &filters(&["jira"], &["ticket"], Some(7), &["mara"]),
            10,
            50,
        );
        for present in [
            "i.source_id = any($2)",
            "i.kind = any($3)",
            "i.item_updated_at >= now() - make_interval(days => $4)",
            "i.author = any($5)",
        ] {
            assert!(
                built.sql.contains(present),
                "{present} missing from\n{}",
                built.sql
            );
        }
    }

    /// An `updated:` window Postgres cannot subtract must be clamped, never
    /// saturated.
    ///
    /// `updated:99999999d` is one paste away and parses to exactly that. The
    /// old code bound `i32::MAX`, which is *guaranteed* to raise `timestamp out
    /// of range` -- so the saturation turned a harmless over-wide filter into
    /// an error on the launcher's hot path.
    #[test]
    fn an_over_wide_updated_window_is_clamped_rather_than_saturated() {
        assert_eq!(clamp_days(7), 7);
        assert_eq!(
            clamp_days(MAX_UPDATED_WITHIN_DAYS.cast_unsigned()),
            MAX_UPDATED_WITHIN_DAYS
        );
        for days in [99_999_999_u32, u32::MAX, i32::MAX.cast_unsigned()] {
            assert_eq!(clamp_days(days), MAX_UPDATED_WITHIN_DAYS, "{days}");
        }
        let built = search_sql(
            &[&LIVE_ITEM],
            Some("x"),
            false,
            &EffectiveFilters {
                updated_within_days: Some(u32::MAX),
                ..EffectiveFilters::default()
            },
            10,
            50,
        );
        assert!(built.binds.contains(&Bind::I32(MAX_UPDATED_WITHIN_DAYS)));
        assert!(!built.binds.contains(&Bind::I32(i32::MAX)));
    }

    /// `mine` with nobody behind it must still filter.
    ///
    /// The user asked for their own work; knobas does not know who they are.
    /// Returning everything would be a filter that silently did nothing.
    #[test]
    fn mine_without_an_identity_binds_an_empty_array_rather_than_dropping_the_filter() {
        let built = search_sql(
            &[&LIVE_ITEM],
            Some("x"),
            false,
            &EffectiveFilters {
                mine: true,
                ..EffectiveFilters::default()
            },
            10,
            50,
        );
        assert!(built.sql.contains("i.author = any("), "{}", built.sql);
        assert!(built.binds.contains(&Bind::Texts(Vec::new())));
    }

    #[test]
    fn a_text_free_query_browses_by_recency_instead_of_ranking() {
        let browse = search_sql(
            &[&LIVE_ITEM],
            None,
            false,
            &filters(&["jira"], &[], None, &[]),
            10,
            50,
        );
        assert!(!browse.sql.contains("ts_rank_cd"), "{}", browse.sql);
        assert!(!browse.sql.contains("ts_headline"), "{}", browse.sql);
        assert!(
            !browse.sql.contains("websearch_to_tsquery"),
            "{}",
            browse.sql
        );
        assert!(!browse.sql.contains("cross join q"), "{}", browse.sql);
        assert!(browse.sql.contains("order by"), "{}", browse.sql);
        assert!(browse.sql.contains("0::real as rank"), "{}", browse.sql);
        assert!(
            browse.sql.contains("null::text as snippet"),
            "{}",
            browse.sql
        );
        // The filter still applies, and it is still a bind.
        assert!(
            browse.sql.contains("i.source_id = any($1)"),
            "{}",
            browse.sql
        );
    }

    /// The per-group total must be a grouped aggregate over the match set, not
    /// a window partition riding on every matching row (M0 carry-over: the
    /// seeded query's `count(*) over (partition by kind)` forced a second full
    /// sort of every match on the launcher's hot path).
    #[test]
    fn the_per_kind_total_costs_one_grouped_aggregate_not_a_second_sort() {
        let built = search_sql(
            &[&LIVE_ITEM],
            Some("sepa"),
            false,
            &EffectiveFilters::default(),
            10,
            50,
        );
        assert!(
            built
                .sql
                .contains("select kind, count(*) as kind_total from m group by kind"),
            "{}",
            built.sql
        );
        assert!(
            !built.sql.contains("count(*) over"),
            "the per-kind total is back on a window partition:\n{}",
            built.sql
        );
        // One window function only: `row_number`, which is the per-kind cap.
        assert_eq!(built.sql.matches(" over (").count(), 1, "{}", built.sql);
        // And the match set is scanned once, for both readers of it.
        assert!(built.sql.contains("m as materialized ("), "{}", built.sql);
    }

    /// A kind whose rows the global limit cut must still come back, so the
    /// group header can show a real count.
    #[test]
    fn totals_outer_join_the_page_so_a_cut_kind_keeps_its_count() {
        let built = search_sql(
            &[&LIVE_ITEM],
            Some("sepa"),
            false,
            &EffectiveFilters::default(),
            10,
            50,
        );
        assert!(
            built
                .sql
                .contains("from totals t\n  left join detail d on d.kind = t.kind"),
            "{}",
            built.sql
        );
    }

    /// `ts_headline` re-parses the document per row, so it must see the page
    /// and not the match set.
    #[test]
    fn the_headline_runs_after_the_limit() {
        let built = search_sql(
            &[&LIVE_ITEM],
            Some("sepa"),
            false,
            &EffectiveFilters::default(),
            10,
            50,
        );
        let limit = built.sql.find("limit $").expect("a limit");
        let headline = built.sql.find("ts_headline").expect("a headline");
        assert!(limit < headline, "{}", built.sql);
        // And it reads the page, not the corpus.
        assert!(built.sql.contains("from picked p"), "{}", built.sql);
    }

    /// The mirror is read through the view migration 0002 added, and `fts` is
    /// matched against rather than selected (interfaces §1).
    #[test]
    fn the_corpus_is_the_live_view_and_fts_is_never_selected() {
        let built = search_sql(
            &[&LIVE_ITEM],
            Some("sepa"),
            false,
            &EffectiveFilters::default(),
            10,
            50,
        );
        assert!(built.sql.contains("sync.live_item i"), "{}", built.sql);
        assert!(!built.sql.contains("sync.item "), "{}", built.sql);
        // `select *` over a CTE this module defined is fine -- its columns are
        // the ones `m` named. What must never happen is `select *` over the
        // mirror itself, whose `fts` is a tsvector that panics when read into a
        // struct (interfaces §1).
        assert!(!built.sql.contains("select * from sync"), "{}", built.sql);
        assert!(!built.sql.contains("select i.*"), "{}", built.sql);
        // `fts` appears exactly twice, and both occurrences are accounted
        // for: ranked and matched against. Neither is a projection, which is
        // what would panic.
        assert_eq!(built.sql.matches("i.fts").count(), 2, "{}", built.sql);
        assert_eq!(
            built.sql.matches("ts_rank_cd(i.fts, q.tsq)").count(),
            1,
            "{}",
            built.sql
        );
        assert_eq!(
            built.sql.matches("i.fts @@ q.tsq").count(),
            1,
            "{}",
            built.sql
        );
    }

    /// The M4 seam: a second corpus unions in without a second query.
    #[test]
    fn a_second_corpus_unions_into_the_same_statement() {
        const OTHER: Corpus = Corpus {
            relation: "sync.other o",
            entity_id: "o.entity_id",
            kind: "o.kind",
            source_id: "o.source_id",
            title: "o.title",
            fts: "o.fts",
            headline_text: "o.title",
            // No author column: an author filter must exclude this corpus
            // rather than be quietly dropped for it.
            author: None,
            updated_at: "o.updated_at",
            synced_at: "o.synced_at",
            path: "null::text",
            scope: Some("o.archived is false"),
        };
        let built = search_sql(
            &[&LIVE_ITEM, &OTHER],
            Some("sepa"),
            false,
            &filters(&["jira"], &[], None, &["mara"]),
            10,
            50,
        );
        assert_eq!(built.sql.matches("union all").count(), 2, "{}", built.sql);
        // One bind per filter, shared by both branches -- not one per branch.
        assert_eq!(built.binds.len(), 6, "{}", built.sql);
        assert_eq!(built.sql.matches("= any($2)").count(), 2, "{}", built.sql);
        // The scope travels with the corpus, into the match *and* the detail.
        assert_eq!(
            built.sql.matches("o.archived is false").count(),
            2,
            "{}",
            built.sql
        );
        // An author filter over a corpus with no author column excludes it.
        assert!(built.sql.contains("and false"), "{}", built.sql);
        // And the two branches cannot read each other's rows.
        assert!(built.sql.contains("where p.corpus = 0"), "{}", built.sql);
        assert!(built.sql.contains("where p.corpus = 1"), "{}", built.sql);
    }
}
